KS-12-5 create
Skip314/KotlinSprint pull request #62
Opened 2024-03-27 20:07 UTC by Skip314

2024-03-29 19:36 UTC, ievetrovdev requested changes

2024-03-29 19:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +
лишняя пустая строка, вижу что ты ее везде ставишь. Но не совсем понимаю функциональное назначение. Автоформатирование ее не убирает?

2024-03-29 19:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +    val isOsadki: Boolean,
в целом, не против транслитерации слов, но пусть будет единообразно. Если выше на английском, то и во всем документе на английском

2024-03-29 19:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +    day1.getWeatherOfMonth()
название get... - подразумевает что метод что-то возвращает.
Тогда лучше fill... или generate...

2024-03-29 19:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +            listOfWeatherOsadki.add(java.util.Random().nextBoolean())
Random можно создать один раз, а не каждый раз в цикле

2024-03-31 08:45 UTC, Skip314 commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +
не убирает. Мы же в функциях делаем пустую строку, почему тут не надо?

2024-03-31 08:46 UTC, Skip314 commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +            listOfWeatherOsadki.add(java.util.Random().nextBoolean())
разве тогда она не будет везде одной и той же? тут она создает ся и сразу помещается в список не создавая переменную, чего в этом плохого ?

2024-04-10 22:01 UTC, ievetrovdev approved these changes
В целом ок, в следующий раз постарайся переводить названия, чтобы из них составлять единообразные переменные

2024-04-10 22:01 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +    val isOsadki: Boolean,
Не исправлено

2024-04-10 22:01 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +    println("Средняя ночная температура в месяце: ${day1.getMidNumList(day1.listOfWeatherDay)}")
Решение рабочее, а еще можно решить с использованием extension функции average().

2024-04-10 22:08 UTC, ievetrovdev approved these changes

2024-04-10 22:08 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +
в функциях пустая строка может ставиться в теле метода. и то это не обязательное требование, но часто может помочь сделать код менее монолитным

[Согласно конвенции](https://kotlinlang.org/docs/coding-conventions.html#class-headers) в свойствах класса (как и в параметрах метода) мы не ставим пустые строки.

2024-04-10 22:11 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +
Да, ты прав. Не убирает :(
И все же в методах и конструкторах не нужны пустые строки после открывающей скобки:
https://kotlinlang.org/docs/coding-conventions.html#method-calls

2024-04-10 22:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12_5.kt
> +            listOfWeatherOsadki.add(java.util.Random().nextBoolean())
Строго говоря, тут создается два объекта: Random и Boolean.
Если записать чуть подробней:
```Kotlin
// ...
val random = java.util.Random()
listOfWeatherRain.add(random.nextBoolean())
```
Но нет смысла DAY_IN_MONTH раз создавать java.util.Random, можно вынести его за цикл

2024-04-11 05:52 UTC, merged